INSERT INTO books(title, description, stock, sale_price, available) VALUES ('El Conde de Montecristo', 'Edmond Dantes es traicionado por su íntimo amigo Fernand Mondego, quien lo acusa falsamente de haber colaborado en la fuga de Napoleón para arrebatarle a su novia, Mercedes. Encarcelado durante años en las mazmorras de la isla de If, Edmond idea su plan de venganza y logra escapar gracias a la ayuda del preso Faria, quien le revela la existencia de un fabuloso tesoro. Tras una milagrosa fuga, Edmond se convierte en el misterioso y acaudalado Conde de Montecristo para llevar a cabo su venganza.', 10, 100.0, true);
INSERT INTO books(title, description, stock, sale_price, available) VALUES ('El Psicoanalista', '«Feliz aniversario, doctor. Bienvenido al primer día de su muerte.» Así comienza el anónimo que recibe el psicoanalista Frederick Starks, y que le obliga a emplear toda su astucia y rapidez para, en quince días, averiguar quién es el autor de esa amenazadora misiva que promete hacerle la vida imposible. De no conseguir su objetivo, deberá elegir entre suicidarse o ser testigo de cómo, uno tras otro, sus familiares y conocidos mueren por obra de un psicópata decidido a llevar hasta el final su sed de venganza.', 1, 80.0, true);
INSERT INTO books(title, description, stock, sale_price, available) VALUES ('El Resplandor', 'Jack Torrance se convierte en cuidador de invierno en el Hotel Overlook, en Colorado, con la esperanza de vencer su bloqueo con la escritura. Se instala allí junto con su esposa, Wendy, y su hijo, Danny, que está plagado de premoniciones psíquicas. Mientras la escritura de Jack no fluye y las visiones de Danny se vuelven más preocupantes, Jack descubre oscuros secretos del hotel y comienza a convertirse en un maníaco homicida, empeñado en aterrorizar a su familia.', 7, 120.0, true);
INSERT INTO books(title, description, stock, sale_price, available) VALUES ('Misery', 'Misery es un relato obsesivo que sólo podía escribir Stephen King. Un escritor sufre un grave accidente y recobra el conocimiento en una apartada casa en la que vive una misteriosa mujer, corpulenta y de extraño carácter. Se trata de una antigua enfermera, involucrada en varias muertes misteriosas ocurridas en diversos hospitales. Esta mujer es capaz de los mayores horrores, y el escritor, con las piernas rotas y entre terribles dolores, tiene que luchar por su vida.', 3, 90.0, true);
INSERT INTO books(title, description, stock, sale_price, available) VALUES ('El Silencio de la Ciudad Blanca', 'Libro recomendado', 1, 70.5, false);
INSERT INTO books(title, description, stock, sale_price, available) VALUES ('La Isla Siniestra', 'Verano de 1954. Los agentes judiciales Teddy Daniels y Chuck Aule son enviados a una remota isla del puerto de Boston para investigar la desaparición de una peligrosa asesina recluida en el hospital psiquiátrico Ashecliffe, un centro penitenciario para criminales perturbados dirigido por el siniestro doctor John Cawley. Pronto descubrirán que el centro guarda muchos secretos y que la isla esconde algo más peligroso que los pacientes.', 2, 85.72, true);
INSERT INTO books(title, description, stock, sale_price, available) VALUES ('Dr. Sueño', 'Dan, alcohólico y traumatizado por lo que le pasó siendo un niño en el hotel Overlook, conoce a Abra, una adolescente que posee el mismo don que él. Dan tratará de salvar a Abra de un grupo de siniestros personajes que ansían la inmortalidad y aspiran alcanzarla alimentándose de los poderes psíquicos de gente como ellos.', 0, 70.0, true);

INSERT INTO sales(customer_email, price, sale_date, book_id) VALUES ('jjmp@mail.com', 90.3, '2022-08-18', 1);
INSERT INTO sales(customer_email, price, sale_date, book_id) VALUES ('milla@mail.com', 97.22, '2021-01-21', 1);
INSERT INTO sales(customer_email, price, sale_date, book_id) VALUES ('carlos@mail.com', 100.0, '2022-07-07', 3);
INSERT INTO sales(customer_email, price, sale_date, book_id) VALUES ('jjmp@mail.com', 60.0, '2022-08-18', 2);
INSERT INTO sales(customer_email, price, sale_date, book_id) VALUES ('jjmp@mail.com', 70.0, '2022-08-18', 4);

INSERT INTO likes(book_id, customer_email) VALUES (1, 'jjmp@mail.com');
INSERT INTO likes(book_id, customer_email) VALUES (1, 'milla@mail.com');
INSERT INTO likes(book_id, customer_email) VALUES (2, 'jjmp@mail.com');